qemu: update to latest master code

diff --git a/tools/qemu_dev_start b/tools/qemu_dev_start
--- a/tools/qemu_dev_start
+++ b/tools/qemu_dev_start
@@ -16,8 +16,8 @@
 #    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 #
 # ARG_OPTIONAL_SINGLE([libremesh-workdir],[],[Optional path to a libremesh working directory to include it as a layer over the rootfs.])
-# ARG_OPTIONAL_SINGLE([monitor-port],[],[Qemu monitor port],[45454])
-# ARG_OPTIONAL_BOOLEAN([enable-wan],[],[Enable wan (needs dnsmasq installed)],[])
+# ARG_OPTIONAL_SINGLE([node-id],[],[An ID number from 0 to 9. Use this when running multiple qemu nodes, each node must have a different ID.],[0])
+# ARG_OPTIONAL_SINGLE([enable-wan],[],[Provide the node with NATed access to the local netork. An ifc must be provided, eg wlan0. Needs dnsmasq installed.)])
 # ARG_OPTIONAL_BOOLEAN([serial],[],[Start the serial terminal],[on])
 # ARG_OPTIONAL_BOOLEAN([verbose],[],[Turn on verbose mode],[])
 # ARG_POSITIONAL_SINGLE([rootfs],[Path to a x86-64-generic-rootfs.tar.gz],[])
@@ -25,18 +25,18 @@
 # ARG_HELP([Helper to run libremesh in a qemu x86_64 for development purposes])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.8.1 one line above ###
+### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, see https://argbash.io for more info
+# Generated online by https://argbash.io/generate
 
 
 die()
 {
-	local _ret=$2
-	test -n "$_ret" || _ret=1
-	test "$_PRINT_HELP" = yes && print_help >&2
+	local _ret="${2:-1}"
+	test "${_PRINT_HELP:-no}" = yes && print_help >&2
 	echo "$1" >&2
-	exit ${_ret}
+	exit "${_ret}"
 }
 
 
@@ -51,8 +51,8 @@ begins_with_short_option()
 _positionals=()
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_libremesh_workdir=
-_arg_monitor_port="45454"
-_arg_enable_wan="off"
+_arg_node_id="0"
+_arg_enable_wan=
 _arg_serial="on"
 _arg_verbose="off"
 
@@ -60,12 +60,12 @@ _arg_verbose="off"
 print_help()
 {
 	printf '%s\n' "Helper to run libremesh in a qemu x86_64 for development purposes"
-	printf 'Usage: %s [--libremesh-workdir <arg>] [--monitor-port <arg>] [--(no-)enable-wan] [--(no-)serial] [--(no-)verbose] [-h|--help] <rootfs> <ramfs>\n' "$0"
+	printf 'Usage: %s [--libremesh-workdir <arg>] [--node-id <arg>] [--enable-wan <arg>] [--(no-)verbose] [-h|--help] <rootfs> <ramfs>\n' "$0"
 	printf '\t%s\n' "<rootfs>: Path to a x86-64-generic-rootfs.tar.gz"
 	printf '\t%s\n' "<ramfs>: Path to a x86-64-ramfs.bzImage"
 	printf '\t%s\n' "--libremesh-workdir: Optional path to a libremesh working directory to include it as a layer over the rootfs. (no default)"
-	printf '\t%s\n' "--monitor-port: Qemu monitor port (default: '45454')"
-	printf '\t%s\n' "--enable-wan, --no-enable-wan: Enable wan (needs dnsmasq installed) (off by default)"
+	printf '\t%s\n' "--node-id: An ID number from 0 to 9. Use this when running multiple qemu nodes, each node must have a different ID. (default: '0')"
+	printf '\t%s\n' "--enable-wan: Provide the node with NATed access to the local netork. An ifc must be provided, eg wlan0. Needs dnsmasq installed. (no default)"
 	printf '\t%s\n' "--serial, --no-serial: Start the serial terminal (on by default)"
 	printf '\t%s\n' "--verbose, --no-verbose: Turn on verbose mode (off by default)"
 	printf '\t%s\n' "-h, --help: Prints help"
@@ -87,17 +87,21 @@ parse_commandline()
 			--libremesh-workdir=*)
 				_arg_libremesh_workdir="${_key##--libremesh-workdir=}"
 				;;
-			--monitor-port)
+			--node-id)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_monitor_port="$2"
+				_arg_node_id="$2"
 				shift
 				;;
-			--monitor-port=*)
-				_arg_monitor_port="${_key##--monitor-port=}"
+			--node-id=*)
+				_arg_node_id="${_key##--node-id=}"
 				;;
-			--no-enable-wan|--enable-wan)
-				_arg_enable_wan="on"
-				test "${1:0:5}" = "--no-" && _arg_enable_wan="off"
+			--enable-wan)
+				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+				_arg_enable_wan="$2"
+				shift
+				;;
+			--enable-wan=*)
+				_arg_enable_wan="${_key##--enable-wan=}"
 				;;
 			--no-serial|--serial)
 				_arg_serial="on"
@@ -152,35 +156,48 @@ parse_commandline "$@"
 handle_passed_args_count
 assign_positional_args 1 "${_positionals[@]}"
 
-# OTHER STUFF GENERATED BY Argbash
+#####################
 
-### END OF CODE GENERATED BY Argbash (sortof) ### ])
-# [ <-- needed because of Argbash
-### START OF CODE GENERATED BY Argbash v2.8.1 one line above, https://argbash.io/generate ###
 
-if [ "$_arg_verbose" == "on" ]; then
+if [[ "$_arg_verbose" == "on" ]]; then
     set -x
 fi
 
-# LAN ifc. We may use a DHCP client, but we are forcing a fixed ip
-ip tuntap add name lime_tap0 mode tap
-ip addr add 10.13.0.99/24 dev lime_tap0
-ip link set lime_tap0 up
+BRIDGE_IFC="lime_br0"
+NODE_ID="${_arg_node_id}"
+LAN_MAC="52:00:00:ab:cd:0${NODE_ID}"
+WAN_MAC="52:00:00:ab:cd:a${NODE_ID}"
+LAN_IFC="lime_tap${NODE_ID}0"
+WAN_IFC="lime_tap${NODE_ID}1"
+OWN_LAN_IP="10.13.0.2/16"
 
-if [ "$_arg_enable_wan" == "on" ]; then
+
+if [ ! -e "/sys/class/net/$BRIDGE_IFC" ]; then
+    ip link add name "$BRIDGE_IFC" type bridge
+    ip link set "$BRIDGE_IFC" up
+    ip addr add "$OWN_LAN_IP" dev "$BRIDGE_IFC"
+fi
+
+# No IP for the tap LAN ifc
+ip tuntap add name "$LAN_IFC" mode tap
+ip link set "$LAN_IFC" up
+ip link set "$LAN_IFC" master "$BRIDGE_IFC"
+
+
+if [ -n "$_arg_enable_wan" ]; then
     # WAN ifc
-    ip tuntap add name lime_tap1 mode tap
-    ip addr add 172.99.0.1/24 dev lime_tap1
-    ip link set lime_tap1 up
+    ip tuntap add name "$WAN_IFC" mode tap
+    ip addr add 172.99.0.1/24 dev "$WAN_IFC"
+    ip link set "$WAN_IFC" up
 
     # DHCP server for WAN ifc
-    dnsmasq -F 172.99.0.100,172.99.0.100 --dhcp-option=3,172.99.0.1 -i lime_tap1 --dhcp-authoritative --log-dhcp
+    dnsmasq -F 172.99.0.100,172.99.0.100 --dhcp-option=3,172.99.0.1 -i "$WAN_IFC" --dhcp-authoritative --log-dhcp
 
     # enable forwarding and NAT
     echo 1 > /proc/sys/net/ipv4/ip_forward
-    iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
+    iptables -t nat -A POSTROUTING -o "$_arg_enable_wan" -j MASQUERADE
     iptables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-    iptables -A FORWARD -i  lime_tap1  -o wlan0 -j ACCEPT
+    iptables -A FORWARD -i  "$WAN_IFC"  -o "$_arg_enable_wan" -j ACCEPT
 fi
 
 # Convert the rootfs.tar.gz into a cpio file
@@ -204,7 +221,8 @@ cd /tmp/lime_rootfs
 find . | cpio --quiet -o -H newc  > /tmp/lime_rootfs.cpio
 cd - > /dev/null
 
-MONITOR_PORT=$_arg_monitor_port
+MONITOR_PORT="4545${NODE_ID}"
+MAIN_SERIAL_PORT="4546${NODE_ID}"
 
 SERIAL=''
 if [ "$_arg_serial" == "on" ]; then
@@ -227,23 +245,26 @@ qemu_args=( \
     -object rng-random,filename=/dev/urandom,id=rng0
     -device virtio-rng-pci,rng=rng0
     # Enable Telnet to the main serial
-    -serial telnet:localhost:45455,server,nowait
+    -serial telnet:localhost:${MAIN_SERIAL_PORT},server,nowait
     # LAN interface
-    -netdev tap,id=hostnet0,ifname=lime_tap0,script=no,downscript=no
-    -device e1000,netdev=hostnet0,id=net0,mac=52:00:00:ab:cd:00,bus=pci.0,addr=0x3
+    -netdev tap,id=hostnet0,ifname="${LAN_IFC}",script=no,downscript=no
+    -device e1000,netdev=hostnet0,id=net0,mac="${LAN_MAC}",bus=pci.0,addr=0x3
     # WAN interface
-    -netdev tap,id=hostnet1,ifname=lime_tap1,script=no,downscript=no
-    -device e1000,netdev=hostnet1,id=net1,mac=52:00:00:ab:cd:01,bus=pci.0,addr=0x4
+    -netdev tap,id=hostnet1,ifname="${WAN_IFC}",script=no,downscript=no
+    -device e1000,netdev=hostnet1,id=net1,mac="${WAN_MAC}",bus=pci.0,addr=0x4
 )
 
 exec qemu-system-x86_64 "${qemu_args[@]}"
 
-# cleanup
-ip tuntap del name lime_tap0 mode tap
 
-if [ "$_arg_enable_wan" == "on" ]; then
-    ip tuntap del name lime_tap1 mode tap
+# cleanup
+ip tuntap del name ${LAN_IFC} mode tap
+
+if [ -n "$_arg_enable_wan" ]; then
+
+    ip tuntap del name "${WAN_IFC}" mode tap
+
     # End dnsmasaq
     kill -TERM `cat /var/run/dnsmasq.pid`
+
 fi
-# ] <-- needed because of Argbash
